### ISSUE TITLE
This project was an inspiration for making a new one: https://github.com/rogeriomm/aws-lab

### ISSUE THREAD

**Issue by rogeriomm** [pvarentsov/terraform-aws-free-tier#2]
Terraform AWS free tier, EC2/RDS/Lambda/S3. Docker running on EC2, Traefik reverse proxy, Lets Encrypt, dynamic DNS, OpenVPN: https://github.com/rogeriomm/aws-lab

**Comment by pvarentsov** [comment]
Hi, it's cool. I could share the link of you project in the readme. For example, in a "Similar Projects" section.

**Comment by rogeriomm** [comment]
> Hi, it's cool. I could share the link of you project in the readme. For example, in a "Similar Projects" section.

Sure, I'll do as well!
